version: '3.5'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: jitsi/etherpad:latest
        restart: ${RESTART_POLICY:-unless-stopped}
        env_file: .env.etherpad
        expose:
          - '9001'
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
    # WBO: whiteboard:
    wbo:
        image: lovasoa/wbo:v1.17.0
        restart: ${RESTART_POLICY:-unless-stopped}
        env_file: .env.etherpad
        expose:
          - '80'
        volumes:
            - ${CONFIG}/wbo:/opt/app/server-data:Z
        networks:
            meet.jitsi:
                aliases:
                    - wbo.meet.jitsi
